= jumper

This project is for the purpose of learning how to make a basic game using
vanilla HTML, javascript, and css. It is a game where a user controls a
continuously jumping character left and right to land on randomly placed,
advancing platforms. If the character falls below the game stage, it is game
over. The higher the user goes, the higher the score.

== code development

This project was created using https://code.visualstudio.com[VS Code].

== edit image svg source

Svg images in the `./asset-source` directory were created using
https://inkscape.org[Inkscape].

== compress SVG files

Used the online SVG compression tool https://www.svgminify.com/[SVG Minify] to
make all SVG images as small as possible.

For the best results with SVG Minify, I used Inkscape before uploading to:

. deleted all unnecessary objects and layers from the SVG
. select [Clean Up Document] from the [File] menu
. save as a new SVG with the file type as "Plain SVG (*.svg)"

== favicon generation

Used https://realfavicongenerator.net/[Real Favicon Generator] to help create
the favicons and related resources need for the website to support different
browsers/operating systems. It supports PNG, JPG, and SVG

== compress png files

Used the online PNG compression tool https://tinypng.com/[TinyPNG] to make
all PNG images as small as possible.

== deploy to github pages

In VS Code's [Terminal] menu, click [Run Task...] and select
[Publish to github pages].

You can also run the following command in the terminal at the root of the
project.

[source,sh]
----
git subtree push --prefix website origin gh-pages
----

== pwa
=== image sizes needed

https://love2dev.com/blog/easily-create-a-baseline-set-of-progressive-web-app-icons/

=== publish to app stores

  To publish your PWA to app stores you can use https://www.pwabuilder.com/pwabuilder[pwabuilder].

== todo

* [ ] Add Sophia character
* [ ] Add game sounds
* [ ] Keep track of personal high score
* [ ] Add narrow platforms
* [ ] Add breaking platforms
* [ ] Add horizontal moving platforms
* [ ] Add vertical moving platforms
* [ ] Add randomly moving platforms
* [ ] Add group high score board (having groups will limit cheating)

'''

* [x] _Add stage and a platform_
* [x] _Draw multiple platforms_
* [x] _Make platforms move down the stage_
* [x] _Place platforms at top of stage after they go below stage bottom_
* [x] _Add jumper character_
* [x] _Make jumper jump off of platforms_
* [x] _Add user keyboard control_
* [x] _Add scoreboard_
* [x] _Add game over_
* [x] _Add jumper image (Caleb), platform, and stage images_
* [x] _Add WASD controls_
* [x] _Make jumper upward draw advancement stop and only move the platforms
downward draw at the same speed the character is able to move up. This will
stop the jumper from moving past the top of the stage._
* [x] _Move stage background image as stage advances to give it a
parallax effect._
* [x] _Add touchscreen controls_
* [x] _Place platforms at random heights_
* [x] _Add full screen mode_
* [x] _Add restart game button on game over screen_
* [x] _Add character selection_
* [x] _Add Zobie character_
* [x] _Force portrait mode_
* [x] _Add favicon_
* [x] _Make game a PWA (progressive web app) that works in github pages._
* [x] _Add Bob character_